/**
 * @h1w0rld/dsh-recovery-resume v0.2.0 —— форк dsh-recovery-resume (flandre2233, 0.1.3),
 * доделан под DSH 0.1.7-rc.2 (format v4).
 *
 * ЧТО ДОБАВЛЕНО относительно базы (base design: только live-агенты):
 *   БУТ-АКТИВАЦИЯ холодных сессий. База ждала, пока сессию кто-нибудь откроет
 *   (агенты в DSH создаются лениво, после рестарта agent/created не стреляет,
 *   и «зависшая» сессия могла висеть неделями). Здесь после старта хоста
 *   сканируются холодные сессии с оборванным хвостом (открытый ход или
 *   turn/end reason=interrupted) и активируются штатным швом
 *   ctx.agents.resume({resumeSessionId, agentOptions, setup}) — тем же,
 *   каким пользуется официальный session-controller:
 *     - resumeWith() самой фабрики сам дописывает interrupted-closers открытому ходу
 *       (repair-on-resume), после чего базовая логика inspectTail видит готовый хвост;
 *     - setup реплицирует composeAgent контроллера: installModelSelection +
 *       presets.mount (если preset есть в observation).
 *   Дальше работает НЕИЗМЕННАЯ логика базы: agent/created → consider →
 *   inspectTail → леджер/бэкофф → agent.followup() с русским промптом.
 *
 * Оставлено как в базе (осознанно): user stop (aborted/user) — финал, не продолжаем;
 * перманентные ошибки (AUTH/QUOTA/контекст) — не продолжаем; 429/сеть — продолжаем
 * с бэкоффом; живой ход не трогаем.
 */

import { buildUserMessage } from './message.js'
import { decideRearm, inspectTail, renderResumePrompt } from './logic.js'
import { extractKeyPoints } from './context.js'
import {
  COOLDOWN_MS,
  MAX_CONSECUTIVE_FAILED_RESUMES,
  checkLedger,
  detectProgressSinceLastAttempt,
  pruneLedger,
  readLedger,
  recordAttemptWithTurn,
  resetAttempts,
  writeLedger,
} from './ledger.js'
import { execFile } from 'node:child_process'
import { randomUUID } from 'node:crypto'
import { readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'

// ─────────────────────────────────────────────────────────────────────────────
// Инлайн-реплика installModelSelection из @deepseek-ai/dsh-agent (по философии
// базы: не зависеть от хостовых пакетов — file:install без pnpm-линков peers).
// Поведение 1:1 с оригиналом (system-prompt/assemble → variables,
// agent/request → provider/model/effort, agent/pre-step → notice о смене модели).
// ─────────────────────────────────────────────────────────────────────────────

function sameRoute(left, right) {
  return left.provider === right.provider && left.model === right.model
}

function routeLabel(route, other) {
  return route.provider === other.provider ? route.model : `${route.provider}/${route.model}`
}

function modelSwitchNotice(previous, selected) {
  const from = routeLabel(previous, selected)
  const to = routeLabel(selected, previous)
  return {
    id: randomUUID(),
    role: 'user',
    content: [{ type: 'text', text: `[model changed: assistant turns above this point were generated by ${from}; the session continues with ${to}]` }],
    source: { kind: 'model-selection', form: 'notice', summary: `${from} → ${to}` },
  }
}

function installModelSelection(agentCtx, selection) {
  const disposeAssembly = agentCtx.on('system-prompt/assemble', async (_assembly, _context, next) => {
    const selected = selection.current
    const assembled = await next()
    selection.assembled = selected
    if (selected === undefined) return assembled
    return { ...assembled, variables: { ...assembled.variables, provider: selected.provider, model: selected.model } }
  })
  const disposeRequest = agentCtx.on('agent/request', async (_payload, next) => {
    const resolved = await next()
    const selected = selection.assembled
    if (selected === undefined) return resolved
    const { reasoningEffort: _inheritedEffort, ...withoutInheritedEffort } = resolved
    return {
      ...withoutInheritedEffort,
      provider: selected.provider,
      model: selected.model,
      ...(selected.reasoningEffort === undefined ? {} : { reasoningEffort: selected.reasoningEffort }),
    }
  })
  const disposeNotice = agentCtx.on('agent/pre-step', async ({ agent, messages, signal, step }, next) => {
    const decision = await next()
    if (decision.kind === 'reject' || signal.aborted) return decision
    if (decision.messages.length === 0 && (step === 1 || messages.length > 0)) return decision
    const selected = selection.assembled
    const previous = agent.session.requestHeader()?.config
    if (selected === undefined || previous === undefined || sameRoute(selected, previous)) return decision
    return { ...decision, messages: [...decision.messages, modelSwitchNotice(previous, selected)] }
  }, { prepend: true })
  return () => {
    disposeAssembly()
    disposeRequest()
    disposeNotice()
  }
}

const PLUGIN = '@h1w0rld/dsh-recovery-resume'

/** Сколько раз одну сессию можно продолжить в пределах одного процесса. */
const MAX_ATTEMPTS_PER_SESSION = 1

/** После idle/created выждать, пока завершатся crash-repair и загрузка (мс). */
const SETTLE_MS = 3000

/** После отправки продолжения выждать перед ре-авторизацией goal (мс). */
const REARM_DELAY_MS = 1500

/** Минимальная пауза между повторными рассмотрениями одной сессии (анти-гонка инжекта). */
const REINJECT_GUARD_MS = 30_000

/** Как долго после старта хоста работает бут-скан холодных сессий. */
const BOOT_SCAN_WINDOW_MS = 20 * 60 * 1000

/** Период бут-скана. */
const BOOT_SCAN_INTERVAL_MS = 7000

/** «Свежая» сессия: лог менялся не позже этого окна (мелкий отсек мусора). */
const BOOT_FRESH_MS = 2 * 60 * 60 * 1000

/** Максимум активаций холодных сессий за один бут (защита от шторма). */
const BOOT_MAX_ACTIVATIONS = 5

/** Ход без turn/end в холодной сессии / последний turn=end=interrupted → кандидат. */
const RESUME_TAIL_REASONS = new Set(['interrupted'])

/** Физические поколения журналов сессий (DSH 0.1.7 = format v4). */
const LOG_GENERATIONS = [
  { name: 'session.v4.jsonl.zstd', version: 4 },
  { name: 'session.v4.jsonl', version: 4 },
  { name: 'session.v3.jsonl.zstd', version: 3 },
  { name: 'session.v3.jsonl', version: 3 },
]

const SESSIONS_ROOT = join(process.env.DSH_HOME || `${process.env.HOME}/.dsh`, 'sessions')

/** Кросс-рестартный леджер (тот же файл, что у базы — совместим по формату). */
const LEDGER_PATH = join(process.env.DSH_HOME || `${process.env.HOME}/.dsh`, 'recovery-attempts.json')

export const name = PLUGIN

export function apply(ctx) {
  console.log(`[${PLUGIN}] apply() — плагин загружен (v0.2.1, бут-активация включена)`)

  /** sessionId → число продолжений в этом процессе. */
  const attempted = new Map()
  /** sessionId → ts последнего инжекта (анти-гонка двойного инжекта). */
  const lastInjectAt = new Map()
  /** Холодные сессии, уже разобранные этим бутом. */
  const bootTried = new Set()
  let bootActivations = 0
  const bootStart = Date.now()

  ctx.inject(['agents'], (scoped) => {
    console.log(`${PLUGIN}: inject(['agents']) выполнен — слушатели установлены, бут-скан запущен`)
    scoped.on('agent/created', ({ agent }) => {
      console.log(`${PLUGIN}: агент создан id=${agent.id} status=${agent.status}`)
      schedule(agent, scoped)
    })
    scoped.on('agent/status', ({ agent, status }) => {
      if (status === 'idle') schedule(agent, scoped)
    })
    startBootScan(scoped)
  })

  function schedule(agent, scoped) {
    const timer = setTimeout(() => {
      try {
        consider(agent, scoped)
      } catch (error) {
        console.error(`${PLUGIN}: ошибка рассмотрения ${agent && agent.id}: ${errText(error)}`)
      }
    }, SETTLE_MS)
    if (typeof timer.unref === 'function') timer.unref()
  }

  function errText(error) {
    return error && error.message ? error.message : String(error)
  }

  function consider(agent, scoped) {
    if (!agent) return
    if (agent.status !== 'idle') {
      console.log(`${PLUGIN}: пропуск ${agent.id} (status=${agent.status} ≠ idle)`)
      return
    }
    const session = agent.session
    if (!session) {
      console.error(`${PLUGIN}: у агента ${agent.id} нет session, пропуск`)
      return
    }
    const sid = session.id
    const done = attempted.get(sid) || 0
    if (done >= MAX_ATTEMPTS_PER_SESSION) {
      console.log(`${PLUGIN}: пропуск ${sid} (в этом процессе уже ${done} продолж.)`)
      return
    }
    const prevInject = lastInjectAt.get(sid) || 0
    if (Date.now() - prevInject < REINJECT_GUARD_MS) return

    let ledgerState = readLedger(LEDGER_PATH)
    if (ledgerState.error !== undefined) {
      console.error(`${PLUGIN}: леджер не читается (считаем пустым): ${ledgerState.error}`)
    }
    let ledger = ledgerState.data

    let events
    try {
      if (typeof session.snapshotEvents === 'function') events = session.snapshotEvents()
      else if (Array.isArray(session.events)) events = session.events
    } catch (error) {
      console.error(`${PLUGIN}: snapshotEvents() упал ${sid}: ${errText(error)}`)
      return
    }
    if (!Array.isArray(events)) {
      console.error(`${PLUGIN}: не прочитать поток событий ${sid} (нет snapshotEvents/events)`)
      return
    }

    let info = inspectTail(events, Date.now())
    if (!info.resume) {
      if (info.skippedError !== undefined) {
        console.log(
          `${PLUGIN}: пропуск ${sid} (прошлый сбой перманентный, повтор бессмыслен: ` +
            `${info.skippedError.why}${info.skippedError.code ? ` code=${info.skippedError.code}` : ''})`,
        )
      }
      return
    }

    console.log(
      `${PLUGIN}: ★ ${sid} найден необработанный обрыв (reason=${info.reason} turnSeq=${info.turnSeq}` +
        `${info.lastTool ? ` lastTool=${info.lastTool}` : ''}) → отправляю продолжение`,
    )

    // Если после прошлой попытки есть прогресс — прошлый успех, сбрасываем бэкофф.
    const progress = detectProgressSinceLastAttempt(ledger, sid, info.turnSeq)
    if (progress.success) {
      console.log(`${PLUGIN}: после прошлого продолжения есть прогресс (turnSeq ${progress.prevSeq} → ${info.turnSeq}) → сброс бэкоффа`)
      ledger = resetAttempts(ledger, sid)
      try {
        writeLedger(LEDGER_PATH, ledger)
      } catch (error) {
        console.error(`${PLUGIN}: запись сброса леджера упала: ${errText(error)}`)
      }
    }

    const verdict = checkLedger(ledger, sid, Date.now())
    if (!verdict.allow) {
      console.log(`${PLUGIN}: пропуск ${sid} (${verdict.why})`)
      return
    }

    let endIndex = -1
    for (let i = events.length - 1; i >= 0; i -= 1) {
      if (events[i] && events[i].type === 'turn/end' && events[i].seq === info.turnSeq) { endIndex = i; break }
    }
    try {
      info = { ...info, keyPoints: extractKeyPoints(events, endIndex) }
    } catch (error) {
      console.error(`${PLUGIN}: извлечение ключевых точек упало (не критично): ${errText(error)}`)
    }

    let message
    try {
      // v4-легальный source: kind ≠ 'plugin' (v4 требует producer-owned kind;
      // чужое поле plugin допускается как «unknown attribution»).
      message = buildUserMessage({
        content: renderResumePrompt(info),
        source: { kind: PLUGIN, plugin: PLUGIN },
      })
    } catch (error) {
      console.error(`${PLUGIN}: сборка сообщения упала: ${errText(error)}`)
      return
    }

    try {
      agent.followup(message)
      attempted.set(sid, done + 1)
      lastInjectAt.set(sid, Date.now())
      console.log(`${PLUGIN}: продолжение поставлено в очередь ${sid} (messageId=${message && message.id})`)
      try {
        const now = Date.now()
        const updated = recordAttemptWithTurn(pruneLedger(ledger, now), sid, now, info.turnSeq)
        writeLedger(LEDGER_PATH, updated)
        console.log(
          `${PLUGIN}: леджер обновлён ${sid} → всего ${updated[sid].attempts}, подряд без прогресса ${updated[sid].consecutive}` +
            ` (лимит ${MAX_CONSECUTIVE_FAILED_RESUMES}, базовый cooldown ${COOLDOWN_MS / 1000}s)`,
        )
      } catch (ledgerWriteError) {
        console.error(`${PLUGIN}: ЗАПИСЬ ЛЕДЖЕРА УПАЛА (анти-разгон не работает!): ${errText(ledgerWriteError)}`)
      }
    } catch (error) {
      console.error(`${PLUGIN}: followup не удался ${sid}: ${errText(error)}`)
    }

    const rearmTimer = setTimeout(() => {
      try {
        rearmGoal(scoped, agent, info.reason)
      } catch (error) {
        console.error(`${PLUGIN}: ре-авторизация goal упала ${sid}: ${errText(error)}`)
      }
    }, REARM_DELAY_MS)
    if (typeof rearmTimer.unref === 'function') rearmTimer.unref()
  }

  function rearmGoal(scoped, agent, reason) {
    let goals
    try {
      goals = scoped.get('goals')
    } catch { goals = undefined }
    if (!goals || typeof goals.get !== 'function') return
    let goal
    try {
      goal = goals.get(agent)
    } catch (error) {
      console.error(`${PLUGIN}: чтение goal не удалось ${agent.id}: ${errText(error)}`)
      return
    }
    const decision = decideRearm(goal, reason)
    if (!decision.rearm) {
      if (goal) console.log(`${PLUGIN}: goal не ре-авторизуется (${decision.why})`)
      return
    }
    try {
      goals.resume(goal.id, decision.revision)
      console.log(`${PLUGIN}: goal ре-авторизован ${decision.id} (rev=${decision.revision})`)
    } catch (error) {
      console.error(`${PLUGIN}: goals.resume не удался ${decision.id}: ${errText(error)}`)
    }
  }

  // ───────────────────────────────────────────────────────────────────────────
  // БУТ-АКТИВАЦИЯ холодных сессий (новое в этом форке)
  // ───────────────────────────────────────────────────────────────────────────

  function startBootScan(scoped) {
    let tickNo = 0
    let busy = false
    const tick = async () => {
      if (Date.now() - bootStart > BOOT_SCAN_WINDOW_MS) {
        console.log(`${PLUGIN}: бут-окно закрыто — скан остановлен`)
        return
      }
      tickNo += 1
      if (busy) {
        // предыдущий тик ещё работает — пропускаем (zstd может быть долгим)
      } else {
        busy = true
        try {
          await bootScan(scoped, tickNo)
        } catch (error) {
          console.error(`${PLUGIN}: бут-скан упал: ${errText(error)}`)
        } finally {
          busy = false
        }
      }
      const t = setTimeout(tick, BOOT_SCAN_INTERVAL_MS)
      if (typeof t.unref === 'function') t.unref()
    }
    const t = setTimeout(tick, 10_000)
    if (typeof t.unref === 'function') t.unref()
  }

  function pickSessionLog(dir) {
    let best
    try {
      for (const gen of LOG_GENERATIONS) {
        try {
          statSync(join(dir, gen.name))
        } catch { continue }
        if (best === undefined || gen.version > best.version) best = gen
      }
    } catch { return undefined }
    return best ? join(dir, best.name) : undefined
  }

  /** Хвост журнала (async, не блокирует event loop): {openTurn, lastEndKind, subagent}. */
  async function readTail(logPath) {
    let raw
    try {
      raw = await new Promise((resolve, reject) => {
        execFile('zstd', ['-dc', logPath], { maxBuffer: 64 * 1024 * 1024, timeout: 20_000 }, (err, stdout) => {
          if (err) reject(err); else resolve(stdout)
        })
      })
    } catch (error) {
      return { error: errText(error) }
    }
    const text = raw.toString('utf8')
    const head = text.slice(0, 4000)
    let lastEndKind
    let openTurn = false
    for (const line of text.split('\n')) {
      if (line.length === 0 || line.length > 200_000) continue
      let e
      try { e = JSON.parse(line) } catch { continue }
      if (e.type === 'turn/end') { lastEndKind = e.data?.reason?.kind ?? (typeof e.data?.reason === 'string' ? e.data.reason : undefined); openTurn = false }
      else if (e.type === 'turn/start') openTurn = true
    }
    return {
      openTurn,
      lastEndKind,
      subagent: head.includes('"origin":"subagent"') || head.includes('"origin": "subagent"'),
    }
  }

  async function activateSession(scoped, sid) {
    // Тот же шов, что у официального session-controller (resumeObserved):
    // observation → preset → setup(installModelSelection + presets.mount).
    const observation = await scoped.get('sessionQuery').observeSession(sid)
    const presetId = observation?.projections?.values?.agentPreset
    const presets = scoped.get('agentPresets')
    let setup
    if (presets && presetId) {
      const resolved = await presets.resolve(presetId)
      setup = async (agentCtx, agent) => {
        installModelSelection(agentCtx, makeSelection(scoped, agent))
        await presets.mount(agentCtx, resolved.id)
      }
    } else {
      setup = (agentCtx, agent) => installModelSelection(agentCtx, makeSelection(scoped, agent))
    }
    const { provider, model } = scoped.get('agentDefaultModel').currentSelection()
    await scoped.agents.resume({ resumeSessionId: sid, agentOptions: { provider, model }, setup })
  }

  /** Реплика controller.selectionFor: персистентный выбор модели сессии. */
  function makeSelection(ctx, agent) {
    const projections = ctx.get('sessionProjections')
    const projectionState = projections?.stateOf?.(agent.session, 'modelSelection')
    if (projectionState === undefined) throw new Error('modelSelection projection is not registered')
    let picked = projectionState.pending === null || projectionState.pending === undefined
      ? undefined
      : {
          provider: projectionState.pending.provider,
          model: projectionState.pending.model,
          ...(projectionState.pending.reasoningEffort === undefined ? {} : { reasoningEffort: projectionState.pending.reasoningEffort }),
        }
    const defaultModel = ctx.get('agentDefaultModel')
    return {
      get current() {
        if (picked !== undefined) return picked
        const loggedHeader = agent.session.requestHeader()
        if (loggedHeader === undefined) return defaultModel.currentSelection()
        const logged = loggedHeader.config
        return {
          provider: logged.provider,
          model: logged.model,
          ...(logged.reasoningEffort === undefined || loggedHeader.adapterDefaults?.reasoningEffort === true
            ? {}
            : { reasoningEffort: logged.reasoningEffort }),
        }
      },
      set current(next) { picked = next },
      consume(provider, model, reasoningEffort) {
        if (picked?.provider !== provider || picked.model !== model || picked.reasoningEffort !== reasoningEffort) return false
        picked = undefined
        return true
      },
      assembled: undefined,
    }
  }

  async function bootScan(scoped, tickNo = 0) {
    let ledger = readLedger(LEDGER_PATH).data
    const now = Date.now()
    let liveCount = 0
    const candidates = []
    let roots
    try {
      roots = readdirSync(SESSIONS_ROOT, { withFileTypes: true })
    } catch { return }
    for (const ws of roots) {
      if (!ws.isDirectory()) continue
      const wsPath = join(SESSIONS_ROOT, ws.name)
      let dirs
      try {
        dirs = readdirSync(wsPath, { withFileTypes: true })
      } catch { continue }
      for (const d of dirs) {
        if (!d.isDirectory() || !d.name.startsWith('session-')) continue
        const sid = d.name
        if (bootTried.has(sid)) continue
        if (scoped.agents.get(sid) !== undefined) { liveCount += 1; continue } // уже жив — не наша работа
        const dir = join(wsPath, sid)
        const logPath = pickSessionLog(dir)
        if (!logPath) continue
        let mtime
        try {
          mtime = statSync(logPath).mtimeMs
        } catch { continue }
        if (now - mtime > BOOT_FRESH_MS) continue
        candidates.push({ sid, logPath, mtime })
      }
    }
    candidates.sort((a, b) => b.mtime - a.mtime)
    // Диагностика: первые 3 тика подробно, дальше — только если есть кандидаты.
    if (tickNo <= 3 || candidates.length > 0) {
      console.log(`${PLUGIN}: бут-скан тик №${tickNo}: живых=${liveCount}, кандидатов на разбор=${candidates.length}`)
    }

    for (const { sid, logPath } of candidates) {
      if (bootActivations >= BOOT_MAX_ACTIVATIONS) {
        console.log(`${PLUGIN}: лимит активаций на бут исчерпан (${BOOT_MAX_ACTIVATIONS})`)
        return
      }
      bootTried.add(sid)
      const tail = await readTail(logPath)
      if (tail.error) {
        console.log(`${PLUGIN}: ${sid} журнал не читается (${tail.error}) — пропуск`)
        continue
      }
      if (tail.subagent) { console.log(`${PLUGIN}: ${sid} subagent — пропуск`); continue }
      const isCandidate = tail.openTurn || RESUME_TAIL_REASONS.has(tail.lastEndKind)
      if (!isCandidate) {
        console.log(`${PLUGIN}: ${sid} хвост не оборван (lastEnd=${tail.lastEndKind ?? 'none'}) — пропуск`)
        continue
      }
      const verdict = checkLedger(ledger, sid, now)
      if (!verdict.allow) {
        console.log(`${PLUGIN}: ${sid} — кандидат, но леджер запрещает (${verdict.why})`)
        continue
      }
      console.log(`${PLUGIN}: ⚡ активирую холодную сессию ${sid} (${tail.openTurn ? 'открытый ход' : `turn/end=${tail.lastEndKind}`})`)
      try {
        activateSession(scoped, sid)
          .then(() => {
            bootActivations += 1
            console.log(`${PLUGIN}: холодная сессия активирована ${sid} — далее сработает штатная логика consider()`)
          })
          .catch((error) => {
            console.error(`${PLUGIN}: активация ${sid} не удалась: ${errText(error)}`)
          })
      } catch (error) {
        console.error(`${PLUGIN}: активация ${sid} упала: ${errText(error)}`)
      }
    }
  }
}

